name: default
created: '2026-01-18 21:11:35'
updated: '2026-01-18 21:11:35'
runs: 1
model: gemini-2.5-pro
turns:
- input: 给我时间盒计划
  run: 1
  output: 'CALL: PLANNER | 安排计划'
  tools_called: []
  expected: ''
  evaluation: ''
  meta: '{"tokens": 410, "cost": 0.0006, "duration_ms": 9568, "ts": "2026-01-18 21:11:35"}'
  history: []
